name: Python CI

on:
  push:
    branches:
      - main  # Trigger when you push to main branch
  pull_request:
    branches:
      - main  # Trigger when you pull from main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner environment

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Use the desired Python version

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from `requirements.txt`

    # 4. Run Black for linting
    - name: Run Black
      run: |
        black .  # Run black on the entire repository

    # 5. Run Flake8 for linting
    - name: Run Flake8
      run: |
        flake8 .  # Run Flake8 on the entire repository

    # 6. Run tests
    - name: Run tests
      run: |
        pytest  # Run tests with pytest (you can replace this with your testing tool)
