name: Python CI

on:
  push:
    branches:
      - main  # Trigger when you push to main branch
  pull_request:
    branches:
      - main  # Trigger when you pull from main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Use the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from `requirements.txt`

    - name: Run Black
      run: black .  # Run black on the entire repository

    - name: Run Flake8
      run: flake8 .  # Run Flake8 on the entire repository

    - name: Run tests
      run: pytest  # Run tests with pytest (you can replace this with your testing tool)

    - name: Setup SSH key
      run: |
        echo "${{ secrets.EC2_INSTANCE_SECRET_KEY }}" > key.pem
        chmod 600 key.pem
    
    - name: Connect to EC2
      run: ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@52.62.115.2

    - name: Kill the server session
      run: screen -S indicators_everywhere -X quit || true

    - name: Create and detach from the server session
      run: |
        screen -dmS indicators_everywhere bash -c "
          cd /home/ec2-user/indicators_everywhere/ &&
          git pull &&
          pip install -r requirements.txt &&
          gunicorn src.app.app:app
        "