name: deploy

on:
    workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Use the desired Python version

    - name: Setup SSH key
      run: |
        echo "${{ secrets.EC2_INSTANCE_SECRET_KEY }}" > key.pem
        chmod 600 key.pem
    
    - name: Connect to EC2 and run commends
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@52.62.115.2 << EOF
          # Kill existing screen session if it exists
          screen -S indicators_everywhere -X quit || true

          # Create new detached screen session
          screen -S indicators_everywhere -d -m
      
          # Execute commands in the screen session
          screen -S indicators_everywhere -X stuff $'cd /home/ec2-user/indicators_everywhere/\n'
          screen -S indicators_everywhere -X stuff $'git pull\n'
          screen -S indicators_everywhere -X stuff $'pip install -r requirements.txt\n'
          screen -S indicators_everywhere -X stuff $'gunicorn -w 2 src.app.app:app\n'
        EOF
