name: test

on:
    workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Use the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from `requirements.txt`

    - name: Run tests
      run: pytest  # Run tests with pytest (you can replace this with your testing tool)
